# -*- coding: utf-8 -*-
"""CIE-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xqtm2jDTIgGqDrR98uVH5V7x_rBo6hk

Clustering
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

df=pd.read_csv("/content/Mall_Customers.csv")
x=df.iloc[:,[3,4]].values

wc=[]
for i in range(1,11):
  k_means=KMeans(n_clusters=i,init='k-means++',random_state=42)
  k_means.fit(x)
  wc.append(k_means.inertia_)

plt.plot(range(1,11),wc)
plt.xlabel("no of cluster")
plt.ylabel("bbsjkdks")

plt.show()

