# -*- coding: utf-8 -*-
"""CIE-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HSn8yeDBZteydnS34qPmOAoBLiMxYq3D
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve
from sklearn.tree import plot_tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
df = pd.read_csv(url, header=None, names=['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
                                          'petal width (cm)', 'Species'])
df.head()

df.shape

df.info()

df.describe()

x=df.drop("Species",)
y=df("Species()

import numpy as np
import pandas as pd
from sklearn.model import Linear_regression
from sklearn.metrics import mean_squared_error

data=pd.read_csv("/content/archive (7).zip")
df.head

df.columns

print(data.head())

print(data.isnull().sum)

print(data.describe())