# -*- coding: utf-8 -*-
"""CIE-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/132H5VqHpTWOO6ZOprd8VE6023brXVmXU
"""

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('/content/mtcars.csv')
plt.figure(figsize=(8, 6))
plt.hist(data['mpg'], bins=10, edgecolor='k', color='red')
plt.title('Histogram of MPG (Miles per gallon)')
plt.xlabel('MPG')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(8, 6))
plt.scatter(data['wt'], data['mpg'], color='green', marker='o')
plt.title('Scatter Plot: Car Weight vs. MPG')
plt.xlabel('Car Weight')
plt.ylabel('MPG')
plt.show()

transmission_counts = data['am'].value_counts()
plt.figure(figsize=(8, 6))
transmission_counts.plot(kind='bar', color='yellow')
plt.title('Frequency Distribution of Transmission Type')
plt.xlabel('Transmission Type (0 = Automatic, 1 = Manual)')
plt.ylabel('Frequency')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(8, 6))
plt.boxplot(data['mpg'], vert=False, notch=True, patch_artist=True, boxprops=dict(facecolor='blue'))
plt.title('Box and Whisker Plot of MPG')
plt.xlabel('MPG')
plt.show()

import pandas as pd
data=pd.DataFrame({'ProductName':['tv','toaster','bulb','top','top'],
               'category':['home','kithen','home','cloth','cloth'],
               'price':[17000,3000,400,3000,2300],
               'Quantity':[1,3,5,3,7]})
data

p=data.pivot_table(index=['category'],values=['price'],aggfunc='mean')
p

data['revenue']=data['price']*data['Quantity']

p=data.pivot_table(index=['category'],values=['price','revenue'],aggfunc='mean')
p