# -*- coding: utf-8 -*-
"""CIE-2 ans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HkgSEPjqbfLyKIobGPTug9jGMJpLJgpz
"""

import pandas as pd
df=pd.read_csv('/content/titanic 7.csv')
df.head()

df.describe()

df.info()

df.duplicated().sum

df['Pclass'].unique

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
url = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
df = pd.read_csv(url)
from scipy import stats
z_scores = np.abs(stats.zscore(df['Fare']))
threshold = 3
outliers = df['Fare'][z_scores > threshold]
plt.figure(figsize=(8, 6))
sns.boxplot(x='Fare', data=df, color='yellow')
plt.title('Box Plot of Fare Column (with Outliers)')
plt.xlabel('Fare')
plt.show()
print("Outlier values for 'Fare' column:")
print(outliers)

import pandas as pd
titanic_data = pd.read_csv('/content/titanic 7.csv')
null_age = titanic_data['Age'].isnull().sum()
null_fare = titanic_data['Fare'].isnull().sum()
mean_age = titanic_data['Age'].mean()
mean_fare = titanic_data['Fare'].mean()
titanic_data['Age'].fillna(mean_age, inplace=True)
titanic_data['Fare'].fillna(mean_fare, inplace=True)
null_age_after = titanic_data['Age'].isnull().sum()
null_fare_after = titanic_data['Fare'].isnull().sum()
print(f"Null values in Age column before: {null_age}")
print(f"Null values in Age column after: {null_age_after}")
print(f"Null values in Fare column before: {null_fare}")
print(f"Null values in Fare column after: {null_fare_after}")

import pandas as pd
import matplotlib.pyplot as plt
titanic_df = pd.read_csv('/content/titanic 7.csv')
titanic_df['Survived'].replace({0: 'Not survived', 1: 'survived'},inplace=True)
survived_counts = titanic_df['Survived'].value_counts()
survived_counts.plot(kind='bar')
plt.show()
titanic_df.head()